{
    'name': 'WhatsApp Web Chats',
    'version': '1.1',
    'category': 'Discuss',
    'summary': 'Provides a WhatsApp Web-like interface for managing WhatsApp chats.',
    'depends': ['mail', 'base', 'web', 'whatsapp', 'product', 'hr', 'auth_signup'],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/ir_config_parameter_data.xml',
        'data/wa_chat_tag_data.xml',
        'data/whatsapp_cron.xml',
        'views/whatsapp_account_views.xml',
        'views/whatsapp_quick_reply_views.xml',
        'views/chats_action.xml',
        'views/product_template_views.xml',
        'views/whatsapp_product_views.xml',
        'views/res_users_views.xml',
        'views/res_config_settings_views.xml',
        'views/login_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'whatsapp_web_chats/static/src/css/chats.css',
            'whatsapp_web_chats/static/src/xml/chats_template.xml',
            'whatsapp_web_chats/static/src/js/chats.js',
        ],
    },
    'installable': True,
    'application': True,
    'post_migrate': 'whatsapp_web_chats.post_migrate',
}
