from . import res_config_settings
from . import wa_chat_tag
from . import whatsapp_account
from . import product_template
from . import whatsapp_product
from . import whatsapp_message
from . import whatsapp_template
from . import mail_message
from . import res_users
from . import discuss_channel
